# Generated by Django 2.2.1 on 2019-05-29 07:19

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img', verbose_name='商品图')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('detail', models.CharField(max_length=200, verbose_name='内容')),
            ],
            options={
                'verbose_name': '资讯',
                'verbose_name_plural': '资讯',
            },
        ),
        migrations.CreateModel(
            name='Classify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='类别')),
                ('title_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='babymall.Classify')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
            },
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.IntegerField(verbose_name='电话')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img', verbose_name='商品图')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('color', models.CharField(max_length=20, verbose_name='颜色')),
                ('num', models.IntegerField(default=1, verbose_name='购买数量')),
                ('price', models.SmallIntegerField(verbose_name='单价')),
                ('subtotal', models.SmallIntegerField(verbose_name='小计')),
            ],
            options={
                'verbose_name': '购物车',
                'verbose_name_plural': '购物车',
            },
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img', verbose_name='商品图')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('ciur_pic', models.SmallIntegerField(verbose_name='现价')),
                ('ori_pic', models.SmallIntegerField(default=None, verbose_name='活动价')),
                ('nub', models.IntegerField(default=0, verbose_name='已售数量')),
                ('discount', models.CharField(default=10, max_length=20, verbose_name='打折')),
                ('cla_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babymall.Classify')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color1', models.CharField(default=None, max_length=20, verbose_name='颜色1')),
                ('color2', models.CharField(default=None, max_length=20, verbose_name='颜色2')),
                ('color3', models.CharField(default=None, max_length=20, verbose_name='颜色3')),
                ('color4', models.CharField(default=None, max_length=20, verbose_name='颜色4')),
                ('com_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babymall.Commodity', verbose_name='商品外键')),
            ],
            options={
                'verbose_name': '颜色',
                'verbose_name_plural': '颜色',
            },
        ),
    ]
