# Generated by Django 2.2.1 on 2019-05-29 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('babymall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classifys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='小类别')),
            ],
            options={
                'verbose_name': '小分类',
                'verbose_name_plural': '小分类',
            },
        ),
        migrations.AlterModelOptions(
            name='classify',
            options={'verbose_name': '大分类', 'verbose_name_plural': '大分类'},
        ),
        migrations.RemoveField(
            model_name='classify',
            name='title_id',
        ),
        migrations.AlterField(
            model_name='classify',
            name='title',
            field=models.CharField(max_length=20, verbose_name='大类别'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='cla_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babymall.Classifys'),
        ),
        migrations.AddField(
            model_name='classifys',
            name='title_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='babymall.Classify'),
        ),
    ]
