# Generated by Django 2.2.1 on 2019-05-30 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('babymall', '0003_commodity_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='babymall.MyUser'),
            preserve_default=False,
        ),
    ]
